# Generated by Django 4.1.5 on 2023-05-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('team_name', models.CharField(max_length=150, null=True)),
                ('leader_name', models.CharField(max_length=150, null=True)),
                ('leader_email', models.EmailField(max_length=150, primary_key=True, serialize=False)),
                ('leader_year', models.IntegerField(null=True)),
                ('member_name', models.CharField(max_length=150, null=True)),
                ('member_email', models.EmailField(max_length=150, null=True)),
                ('member_year', models.IntegerField(null=True)),
                ('logged_in', models.BooleanField(default=False)),
                ('selected_schema', models.IntegerField(null=True)),
                ('final_submission_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('schema_id', models.IntegerField(primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=150, null=True)),
                ('image_url', models.URLField()),
                ('schema_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('team_name', models.CharField(max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('time_taken', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200, null=True)),
                ('asset_url', models.URLField()),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.schema')),
            ],
        ),
    ]
