# Generated by Django 4.2 on 2023-05-12 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='time_taken',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
