# Generated by Django 4.2 on 2023-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_leaderboard_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='time_taken',
            field=models.CharField(max_length=100),
        ),
    ]
