# Generated by Django 4.2 on 2023-04-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
