# Generated by Django 4.2 on 2023-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_leaderboard_id_alter_leaderboard_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leader_branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leader_hosteler',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leader_phoneNo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leader_rollNo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='member_branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='member_hosteler',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='member_phoneNo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='member_rollNo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
