# Generated by Django 4.2 on 2023-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_userprofile_leader_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='leader_email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='leader_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member_email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_schema',
            field=models.IntegerField(null=True),
        ),
    ]
