# Generated by Django 4.2 on 2023-05-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_schema_schema_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='schema_year',
            field=models.IntegerField(),
        ),
    ]
